# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e46bd3ba9f0b8c3f17b231f30cdcf028a2b1e3cc02f8dfc9a7cce7c619096305057c52baf21b40d07cc4deeb1c3abde302d1bf17288ab96a11bd5157dd1fe122

test:
  secret_key_base: f0b443c021bbfa253882185ee1fa48cf830186f6de312a146b03518ccd726eeaf0682dcb01551fbc34a92abf63b8333d2e2e92a9903b1a13e875b317fa3834ec

production:
  secret_key_base: 457ab9f3c373d3a2937c27714d5878e41e8bd596794c370d0a92af424d2a835b261e6fea6bb29f0c0f081f6b7955bc5052faed759c633448bf954e0c39e22cfc
